# Generated by Django 4.2.2 on 2023-06-24 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoice',
            name='expiration_date_cannot_be_past_date',
        ),
    ]
