# Generated by Django 4.2.2 on 2023-06-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_receipt_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='amount_currency',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
