version: '3.8'

services:
  web:
    image: fakebank
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:8080:8000
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  postgres_data: